apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: apps.cloud.cranom.tech
spec:
  group: cloud.cranom.tech
  names:
    kind: Application
    plural: applications
    singular: application
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          # Application Name
          app-name:
            type: string
          # Volumes
          volumes:
            type: array
            items:
              type: object
              properties:
                volume-name:
                  type: string
                path:
                  type: string
          # Port Configuration
          ports:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                internal:
                  type: integer
                  format: int64
                external:
                  type: integer
                  format: int64
                domain:
                  type: string
                SSL:
                  type: boolean
          # Environment variables
          env:
            type: array
            items:
              type: object
              properties:
                name: 
                  type: string
                value: 
                  type: string

    subresources:
      status: {}