apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: application-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: cloud.cranom.tech/vl
    resource: applications
  childResources:
  - apiVersion: v1
    resource: deployments
    updateStrategy:
      method: RollingInPlace
  - apiVersion: v1
    resource: services
    updateStrategy:
      method: Recreate
  hooks:
    sync:
      webhook:
        url: http://crane-dep.crane-op/sync