
# APP
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conveyor-app
  namespace: conveyor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conveyor-app
  template:
    metadata:
      labels:
        app: conveyor-app
    spec:
      containers:
        - name: app
          image: openug/conveyor:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: ETCD_ENDPOINT
              value: http://etcd:2379
            - name: LOKI_ENDPOINT
              value: http://loki:3100
            - name: NATS_URL
              value: nats://nats:4222

---
apiVersion: v1
kind: Service
metadata:
  name: conveyor-app
  namespace: conveyor
spec:
  selector:
    app: conveyor-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

