
# ETCD
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data
  namespace: conveyor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: conveyor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: bitnami/etcd:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2379
            - containerPort: 2380
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"
            - name: ETCD_ADVERTISE_CLIENT_URLS
              value: "http://etcd:2379"
          volumeMounts:
            - name: etcd-storage
              mountPath: /bitnami/etcd
      volumes:
        - name: etcd-storage
          persistentVolumeClaim:
            claimName: etcd-data

---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: conveyor
spec:
  selector:
    app: etcd
  ports:
    - name: client
      port: 2379
      targetPort: 2379
    - name: peer
      port: 2380
      targetPort: 2380