apiVersion: cloud.cranom.tech/v1
kind: Application
metadata:
  name: mysql
spec:
  app-name: mysql
  image: mysql:9.0
  ports:
  - internal: 3306
    external: 3306

  volumes:
  - volume-name: mysql-persistent-storage

  envFrom: mysql-secrets
