apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
type: Opaque
data:
  WORDPRESS_DB_HOST: YXBwbGljYXRpb24tbXlzcWwuY3JhbmUtb3A=
  WORDPRESS_DB_USER: d3BkYg==
  WORDPRESS_DB_PASSWORD: cGFzc3dvcmQ=
  WORDPRESS_DB_NAME: d3BkYg==

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_DATABASE: d3BkYg==
  MYSQL_USER: d3BkYg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=