name: Publish Helm Chart to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - "helm/**" # adjust this to match your chart folder
      - ".github/workflows/helm-publish.yml"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to push to gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.3

      - name: Package Helm chart
        run: |
          mkdir -p charts
          helm package mychart -d charts

      - name: Create index.yaml
        run: |
          helm repo index charts --url https://open-ug.github.io/conveyor

      - name: Publish to GitHub Pages (gh-pages branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./charts
          publish_branch: gh-pages
