name: Publish Conveyor Python Client Package to PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    if: startsWith(github.event.release.tag_name, 'python-v')
    name: Build and Publish Python SDK to PyPI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sdk/python

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build

      - name: Twine check
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
